version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    restart: always
    container_name: mongo
    image: "mongo:3"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - ${DATA_FOLDER_PATH}/mongo/db:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
#      - ${DATA_FOLDER_PATH}/elasticsearch/data:/usr/share/elasticsearch/data
#      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g


  graylog:
    restart: always
    container_name: graylog
    image: graylog/graylog:2.3.2-1
#    image: graylog/graylog:4.1
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
#      - ${DATA_FOLDER_PATH}/graylog/config:/usr/share/graylog/data/config
      - ${DATA_FOLDER_PATH}/graylog/journal:/usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_WEB_ENDPOINT_URI: ${GRAYLOG_WEB_ENDPOINT_URI}
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "${HTTP_IP}:${HTTP_PORT}:9000"
      - "${HTTP_IP}:${HTTP_PORT1}:12201/udp"
      - "${HTTP_IP}:${HTTP_PORT2}:1514/udp"
      - "${HTTP_IP}:${HTTP_PORT3}:12301/udp"
      - "${HTTP_IP}:${HTTP_PORT4}:12302/udp"
